[package]
name = "bpx-api-client"
authors = ["Backpack <security@backpack.exchange>"]
license = "Apache-2.0"
version = "0.2.1"
edition = "2021"
description = "Rust client for Backpack Exchange"

[dependencies]
base64 = { workspace = true }
bpx-api-types = { version = "0.1.2", path = "../types" }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { version = "1", features = ["full"] }
minisign = "0.7.6"
ed25519-compact = "2.1.1"
dotenv = "0.15.0"


[[bin]]
name = "example"
path = "example/main.rs"
